language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

script: phpunit -c app/

env:
    - SYMFONY__TESTDB=mysql
    - SYMFONY__TESTDB=pgsql
    - SYMFONY__TESTDB=sqlite

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - if [[ "$SYMFONY__TESTDB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS partkeepr_test;" -U postgres; fi
  - if [[ "$SYMFONY__TESTDB" == "pgsql" ]]; then psql -c "create database partkeepr_test;" -U postgres; fi
  - if [[ "$SYMFONY__TESTDB" == "mysql" ]]; then mysql -e "DROP TABLE IF EXISTS partkeepr_test;" -uroot; fi
  - if [[ "$SYMFONY__TESTDB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS partkeepr_test;" -uroot; echo "OK"; fi
  - composer self-update
  - composer install --prefer-source --no-interaction
  - app/console cache:warmup --env=test
  - app/console doctrine:schema:create --env=test