imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false


doctrine:
    dbal:
        default_connection: %testdb%
        connections:
            sqlite:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db
            mysql:
                driver:     pdo_mysql
                dbname:     partkeepr_test
                host:       localhost
                user:       travis
            pgsql:
                driver:     pdo_pgsql
                dbname:     partkeepr_test
                host:       localhost
                user:       travis

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        %testdb%:
            tree: true

liip_functional_test:
    cache_sqlite_db: true
    authentication:
        username: "admin"
        password: "admin"


security:
    firewalls:
        main:
            anonymous: ~
            http_basic: ~