imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false


doctrine:
    dbal:
        default_connection: %testdb%
        connections:
            sqlite:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db
                charset:    UTF8
            mysql:
                driver:     pdo_mysql
                dbname:     partkeepr_test
                host:       localhost
                user:       travis
                charset:    UTF8
            pgsql:
                driver:     pdo_pgsql
                dbname:     partkeepr_test
                host:       localhost
                user:       travis
                charset:    UTF8

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        %testdb%:
            tree: true

liip_functional_test:
    cache_sqlite_db: true
    authentication:
        username: "admin"
        password: "admin"

security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
    firewalls:
        main:
            http_basic:
                realm: "Secured Demo Area"
                provider: in_memory
