partkeepr:
  image_cache_directory: %kernel.cache_dir%/imagecache/
  directories:
    iclogo: %kernel.root_dir%/../data/images/iclogo/
    temp: %kernel.root_dir%/../data/temp/
    tempfile: %kernel.root_dir%/../data/files/Temporary/
    footprintattachment: %kernel.root_dir%/../data/files/FootprintAttachment/
    mimetype_icons: %kernel.root_dir%/../src/PartKeepr/MimetypeIconsBundle/Resources/public/images/mimes/