part_keepr_auth:
    resource: "@PartKeeprAuthBundle/Controller/"
    type:     annotation
    prefix:   /

partkeepr_siprefixbundle:
    resource: "@PartKeeprSiPrefixBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc