security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
          algorithm: sha512
          iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern: ^/auth/getSalt
            security: false
        main:
            pattern: ^/api/.*
            wsse:
              realm: "Secured with WSSE" #identifies the set of resources to which the authentication information will apply (WWW-Authenticate)
              profile: "UsernameToken" #WSSE profile (WWW-Authenticate)
              encoder: #digest algorithm
                algorithm: sha512
                encodeHashAsBase64:    true
                iterations: 1

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }