security:
    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm: sha512
          iterations: 1
        FOS\UserBundle\Model\UserInterface:
          algorithm: sha512
          iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    admin:
                        password: x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ONxp3Y3pB37A==
                        roles: 'ROLE_ADMIN'
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern: ^/api/users/getSalt
            security: false
        main:
            stateless: true
            pattern: ^/api/.*
            provider: fos_userbundle
            http_basic:
                provider: fos_userbundle
            wsse:
                realm: "Secured with WSSE" #identifies the set of resources to which the authentication information will apply (WWW-Authenticate)
                profile: "UsernameToken" #WSSE profile (WWW-Authenticate)
                encoder: #digest algorithm
                    algorithm: sha512
                    encodeHashAsBase64:    true
                    iterations: 1

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
